name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - feat/plugin-docs # ⬅️ Tambah baris ini

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v3

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: npm

      - name: 📦 Install Dependencies
        run: npm install

      - name: 🏗️ Build Monorepo
        run: npm run build:all

      - name: 🚀 Deploy ke GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/frontend/out/frontend/docs
          publish_branch: gh-pages
